version: '3.8'
# lancer avec : docker compose -f docker-compose.dev.yml --env-file .env up
services:
  db:
    container_name: mariadb-pfl
    # mysql ou mariadb:11.1-rc ou mariadb:11.0.2-jammy
    image: mariadb:11.0.2-jammy
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD:-motDePasse}
      MARIADB_USER: ${MARIADB_USER:-admin}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD:-pwd}
      MARIADB_DATABASE: ${MARIADB_DATABASE:-dbname}
    ports:
      - ${MARIADB_PORT:-3306}:3306
    volumes:
      # named volumes
      - ./mariadb-data:/var/lib/mariadb
      # seeding scripts
      #- ./init-db:/docker-entrypoint-initdb.d

  adminer:
    container_name: adminer-pfl
    image: adminer:4.8.0-standalone
    restart: always
    environment:
      ADMINER_DEFAULT_SERVER: ${ADMINER_DEFAULT_SERVER:-mysql}
    ports:
      - ${ADMINER_PORT:-8080}:8080

  smtp4dev:
    container_name: smtp4dev-pfl
    image: rnwood/smtp4dev:v3
    restart: always
    environment:
      SMTP4DEV_WEB_INTERFACE_PORT: ${SMTP4DEV_WEB_INTERFACE_PORT:-9080}:9080
      SMTP4DEV_SMTP_SERVER_PORT: ${SMTP4DEV_SMTP_SERVER_PORT:-9025}:25
    ports:
      - ${SMTP4DEV_WEB_INTERFACE_PORT:-9080}:80
      - ${SMTP4DEV_SMTP_SERVER_PORT:-9025}:25

volumes:
  mariadb-data:
